global class AMPOpportunityDataSync {

    WebService static string getOpportunityData(string Id) {
       /* Set<Id> ids = new Set<Id>();
        for (Id i : Id.split(',')) 
            ids.add(i); 
        string appName = 'SFDC';
        string apiKey = AMPUpdateOpportunityFromPortalUser.getAMPApiKey(appName);
        return AMPUpdateOpportunityFromPortalUser.updateOpportunities(ids,appName,apiKey);*/
        return '';
    }
}