// we are not using this class anymore
public class AMPUpdateCObjectData {
    public static void syncData(string cObjectName, string linkID, string email, string source, Set<Id> recordIds) {
    /*String result = '';
        try {
            if(!recordIds.isEmpty()) {
                //Get All fields of Custom Objects
                String[] types = new String[]{cObjectName};
                Schema.DescribeSobjectResult[] results = Schema.describeSObjects(types);
                // For each returned result, get some info
                for(Schema.DescribeSobjectResult res : results) {
                    // Get child relationships
                    Schema.ChildRelationship[] rels = res.getChildRelationships();
                    if (rels.size() > 0) {
                    }
                }
            }
            } catch(Exception ex) {
            result = ex.getMessage(); 
        }*/
    }
}